#!/bin/sh

prefix="/home/ffl/local"
exec_prefix="${prefix}"

libdir="${exec_prefix}/lib"
#datarootdir="${prefix}/share/imalib"
datadir="${datarootdir}"
includedir="${prefix}/include"

package="control_box"
version="0.1"

usage()
{
	cat <<EOF
Usage: $0 [OPTIONS]
Options:
   [--prefix]
   [--version]
   [--libs]
   [--cflags]
EOF
    exit $1
}

if test $# -eq 0; then
    usage 1 1>&2
fi

while test $# -gt 0; do
   case "$1" in
   -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
   *) optarg= ;;
   esac

   case "$1" in
   --prefix=*)
     prefixdirectory=$optarg
   ;;
   --prefix)
     echo_prefix=yes
   ;;
   --cflags)
     echo_cflags=yes
   ;;
   --libs)
     echo_libs=yes
   ;;
   --version)
     echo_version=yes
   ;;
   *)
      echo "Unknown option"
      usage 1 1>&2
   ;;
   esac
   shift
done

if test "$echo_prefix" = "yes"; then
    echo $prefix
fi

if test "$echo_cflags" = "yes"; then
    echo -I$includedir
fi

if test "$echo_libs" = "yes"; then
    echo -L$libdir -lbox_api
fi

if test "$echo_version" = "yes"; then
    echo $version
fi
